### ISSUE TITLE
Milestones and versioning

### ISSUE THREAD

**Issue by petamas** [gsl-lite/gsl-lite#196]
I'm a little bit confused about this project's milestones.

What I see:

- The last released version was 0.34.0 (by @martinmoene)
- PR #172 by @mbeutel increased the gsl_lite_MINOR macro to 35
- There is no 0.35 milestone, but there are 0.36 and 1.0 milestones

My questions are:

- Do you plan to release v0.35, or will the next release be 0.36?
- I there will be a v0.35, which issues are to be in it, and when do you plan to release it?
- What is the versioning policy, what triggers the release of a new version? Are released versions supposed to be more stable in some way? Are there additional checks before a release?

After I'm finished with my not_null-related modifications, I plan to integrate the new version of GSL-Lite into our company's codebase. I'm curious if I should wait for a "named release", or if simply grabbing the HEAD from master is safe enough.

**Comment by mbeutel** [comment]
(First, sorry about the nonsense with me editing your post. It should be back to the original state now.)


In my own projects I usually increment the version number in HEAD after a release and keep it until the next release. This was why I bumped the version number to 0.35 in my PR. But then I noted that Martin used to increment the version number in the final commit for a release (with message "Release X.Y"); following this reasoning, my PR would constitute version 0.35.

I wanted to get a few things straightened out (most notably the Vcpkg integration) before making a release myself, so I didn't push out a release 0.35.


> - Do you plan to release v0.35, or will the next release be 0.36?

My plan is to skip 0.35 and to make 0.36 the next release to avoid version confusion.


> - What is the versioning policy, what triggers the release of a new version? Are released versions supposed to be more stable in some way? Are there additional checks before a release?

Perhaps Martin can comment on how this was handled in the past. This is what I'd like to do:

- There is no stability guarantee for changes only in HEAD, i.e. anything added since the last release may be renamed, removed, have the semantics changed, etc. without further notice.
- A minor-version release should be compatible (in both ABI and API) with the previous minor-version release. Thus, once a change is released, it becomes part of the contract, and subsequent releases *should* not break anyone relying on it.
- The next major-version release is kept in a separate branch (currently "develop").


 > I'm curious if I should wait for a "named release", or if simply grabbing the HEAD from master is safe enough.

If we go with my approach, you should probably await a tagged release. But I'm open for other suggestions :)

In either case, I think our release and versioning policy should be mentioned in the readme.

**Comment by martinmoene** [comment]
Versioning in the past

I incremented the version number just before release. I did have some vague idea that continuing development under that number was not 'ideal', but never thought of incrementing it immediately after a release nor have noticed it's use elsewhere. Looks like a good idea to me :)

My notion of releases does not go much further than the division in major, minor and bug-fix releases. I usually released when I had done a block of work, when someone asked for it, or some such, and so far these have all been minor and bug-fix releases, be it right or not. I haven't had and still haven't enough notion of ABI to include that into versioning :(

You can imagine I'm quite happy to see the thought and effort you are putting into better organizing 'what not' :)

**Comment by mbeutel** [comment]
Martin, thank you for clarifying this.

Would you consider "no stability guarantees for code not under a release tag" an acceptable and reasonable stance? Otherwise we'd need a different branching strategy (e.g. using "develop" for not-yet-final changes).


(In any case, the branch for the next major version should probably be called "vNext" or so, not "develop".)


> I haven't had and still haven't enough notion of ABI to include that into versioning :(

ABI is a difficult thing, and I'm not always quite sure myself where to draw the line. In theory, almost every change we apply could break ABI for someone, but most of those breakages only occur in pathological situations (like taking the address of a particular member function) which we can probably ignore. Also, we always risk ODR violations when we change function definitions, but these are rarely problematic because most functions in *gsl-lite* are probably expanded inline. Sometimes we explicitly accept ODR violation, e.g. when compiling different translation units with different contract settings.

I think we should be mostly concerned with changes to types that are instantiated in user-defined code (as opposed to being used only for metaprogramming). Changes to template parameters, base classes, data members, virtual member functions are usually ABI-breaking and should be avoided.

KDE's guide to ABI compatibility is very helpful:
https://community.kde.org/Policies/Binary_Compatibility_Issues_With_C%2B%2B

**Comment by martinmoene** [comment]
Moritz, thanks for the pointer to KDE's guide to ABI compatibility.

I'd rather not branch for non-major (version) developments, so as a consequence it is acceptable to have "no stability guarantees for [new] code not under a release tag" :)

**Comment by mbeutel** [comment]
[Release 0.36](https://github.com/gsl-lite/gsl-lite/releases/tag/v0.36.0) is now out, and we now document the versioning semantics in the readme:
https://github.com/gsl-lite/gsl-lite#version-semantics
