### ISSUE TITLE
gsl_CONFIG_DEFAULTS_VERSION=1 does not compile without exceptions 

### ISSUE THREAD

**Issue by petamas** [gsl-lite/gsl-lite#254]
1. `gsl::narrow` is defined only if we have exception support, or `gsl_CONFIG_NARROW_THROWS_ON_TRUNCATION` is set to 0. (See discussion in issue #52)
2. `gsl_CONFIG_DEFAULTS_VERSION=1` turns on `gsl_CONFIG_NARROW_THROWS_ON_TRUNCATION`

This means `gsl::narrow` will not be defined in this case. However, the `gsl_lite` namespace unconditionally imports `gsl::narrow`, resulting in a compile error.

My proposed solution is to give a name to `gsl_HAVE( EXCEPTIONS ) || !gsl_CONFIG_NARROW_THROWS_ON_TRUNCATION` and use that to conditionally compile both `gsl::narrow`'s and `gsl_lite::narrow`'s definitions, but I do not know which prefix I should use - is it a gsl_CONFIG, a gsl_FEATURE, or something else?

I think @martinmoene migth be able to help me with this.

**Comment by mbeutel** [comment]
> This means `gsl::narrow` will not be defined in this case. However, the `gsl_lite` namespace unconditionally imports `gsl::narrow`, resulting in a compile error.

Thank you for bringing up this oversight.


> My proposed solution is to give a name to `gsl_HAVE( EXCEPTIONS ) || !gsl_CONFIG_NARROW_THROWS_ON_TRUNCATION` and use that to conditionally compile both `gsl::narrow`'s and `gsl_lite::narrow`'s definitions, but I do not know which prefix I should use - is it a gsl_CONFIG, a gsl_FEATURE, or something else?

If I understand you correctly, you want

```c++
#define gsl_NOT_YET_NAMED gsl_HAVE( EXCEPTIONS ) || !gsl_CONFIG_NARROW_THROWS_ON_TRUNCATION
```

I think that would be neither a `gsl_CONFIG` nor a `gsl_FEATURE`; both are meant to be controllable by the user, which this macro wouldn't be. If anything, it could be named `gsl_HAVE_*`.

However, I'd rather avoid introducing a (non-internal, documented) name for it unless there is a compelling argument for exposing this mode to the library user. Would this be useful anwhere other than in the definition of `namespace gsl_lite`?

**Comment by petamas** [comment]
Yes, it would only be used in two places:
- around the defintion of `gsl::narrow`
- around the `using gsl::narrow` statement in `namespace gsl_lite`
I'd like to introduce a name because if a condition is used in at least two places, then sooner or later, the two uses _will_ diverge, leading to hard-to-find bugs. But it should be an internal macro, not something our users are allowed to see - we could `#undef` it at the end of the header.

My understanding was that `gsl_HAVE` macros describe the environment, regardless of the configuration by the a user. Maybe this macro should simply be called `gsl_NARROW_ENABLED`, without any "functional" prefix?

**Comment by mbeutel** [comment]
Good, then we're in agreement :) `gsl_NARROW_ENABLED_` seems appropriate; I typically use the trailing underscore for internal macros. `#undef`ing them all at the end of the file would be a nice touch, too.

**Comment by petamas** [comment]
OK, I'll prepare the relevant PR in a few days (and this time, it _will_ be a few days).

**Comment by petamas** [comment]
After sleeping on it, wouldn't `gsl_NARROW_CAN_BE_DEFINED_` a better name? Since it is not about enabling/disabling `narrow`, but figuring out if we're able to satisfy the user's configuration.

**Comment by mbeutel** [comment]
Agreed, a name with `ENABLED` in it might make readers think this was a switch they could toggle. But I wouldn't lose sleep over the name of an internal macro only ever used twice :) Either is fine with me, and we can change it anytime later.

**Comment by brooksprumo** [comment]
Hi all, I think I'm running into this issue. I'm compiling for an embedded RTOS using ARM GNU GCC

```
arm-none-eabi-g++ (GNU Tools for Arm Embedded Processors 9-2019-q4-major) 9.2.1 20191025 (release) [ARM/arm-9-branch revision 277599]
```

with exceptions turned off and I am getting this error:

```
./lib/gsl-lite/include/gsl/gsl-lite.hpp: In function 'Stream& gsl::detail::write_to_stream(Stream&, const Span&)':
./lib/gsl-lite/include/gsl/gsl-lite.hpp:3871:36: error: 'narrow' was not declared in this scope
 3871 |     const std::streamsize length = narrow<std::streamsize>( spn.length() );
      |                                    ^~~~~~
./lib/gsl-lite/include/gsl/gsl-lite.hpp:3871:58: error: expected primary-expression before '>' token
 3871 | 
```

It looks like `narrow` is still referenced, even though the `#define`s have prevented it from being defined. As a quick work-around I'm doing:

```
#if gsl_NARROW_CAN_BE_DEFINED_
    const std::streamsize length = narrow<std::streamsize>( spn.length() );
#else
    const std::streamsize length = narrow_cast<std::streamsize>( spn.length() );
#endif
```

Let me know if you need any additional information from me, or if you'd like me to create a new issue. Thank you!

**Comment by mbeutel** [comment]
`narrow<>()` was specified to throw an exception if narrowing occurs (cf. discussion in #52). In particular, the Core Guidelines maintainers [clarified](https://github.com/isocpp/CppCoreGuidelines/issues/1498#issuecomment-540721452) that `narrow<>()` is not a precondition violation.

If you use *gsl-lite* with `gsl_CONFIG_DEFAULTS_VERSION=1` or set `gsl_CONFIG_NARROW_THROWS_ON_TRUNCATION=1` (which I assume you do because you are seeing this error) you get conforming behavior, i.e. `narrow<>()` always throws `narrowing_error` regardless of the contract violation configuration settings. However, because conforming behavior currently isn't achievable if exceptions are not supported, we don't define `narrow<>()` in this case.

I assume you just want a contract-like runtime check that triggers if narrowing occurs? In that case you could use the `narrow_failfast<>()` function. Note, though, that this function is a *gsl-lite* extension and not yet part of the GSL specification (cf. https://github.com/isocpp/CppCoreGuidelines/issues/1552).

> As a quick work-around I'm doing:
>
>     #if gsl_NARROW_CAN_BE_DEFINED_
>        const std::streamsize length = narrow<std::streamsize>( spn.length() );
>     #else
>        const std::streamsize length = narrow_cast<std::streamsize>( spn.length() );
>     #endif

Note that `gsl_NARROW_CAN_BE_DEFINED_` is an undocumented internal macro (indicated by the trailing underscore) and also [undefined at the end of "gsl-lite.hpp"](https://github.com/gsl-lite/gsl-lite/blob/master/include/gsl/gsl-lite.hpp#L4187), so your code will always use the second branch of the `#ifdef` regardless of exception settings and *gsl-lite* configuration.

---

I'm glad you brought up the issue, because I now think it may be better to define `narrow<>()` unconditionally and have it trigger a `static_assert()` which explains the situation if exceptions are unavailable.

**Comment by petamas** [comment]
@mbeutel: I think you misunderstood @brooksprumo's comment: they're calling `gsl::detail::write_to_stream()` indirectly (probably through some `span`-related `operator<<`), which uses `gsl::narrow`:
```
template< class Stream, class Span >
Stream & write_to_stream( Stream & os, Span const & spn )
{
    typename Stream::sentry sentry( os );

    if ( !os )
        return os;

    const std::streamsize length = narrow<std::streamsize>( spn.length() );

    // Whether, and how, to pad
    const bool pad = ( length < os.width() );
    const bool left_pad = pad && ( os.flags() & std::ios_base::adjustfield ) == std::ios_base::right;

    if ( left_pad )
        write_padding( os, os.width() - length );

    // Write span characters
    os.rdbuf()->sputn( spn.begin(), length );

    if ( pad && !left_pad )
        write_padding( os, os.width() - length );

    // Reset output stream width
    os.width(0);

    return os;
}
```

So, the call to the missing `narrow` (and the proposed `#if`) are in GSL-Lite code.

**Comment by petamas** [comment]
Regardless of that, I think always defining `gsl::narrow`, and using a `static_assert` if it should, but cannot throw is a great idea.

**Comment by brooksprumo** [comment]
Thank you for the info, @mbeutel. Here's a bit more info about my use case:

- My platform disables exceptions, so I cannot turn them back on.
- Yes, I am setting `gsl_CONFIG_DEFAULTS_VERSION=1`, because I get the following error if I don't:

```
[Error] gsl-lite.hpp@22,3: #error Header <gsl-lite/gsl-lite.hpp> requires version 1 defaults; set gsl_CONFIG_DEFAULTS_VERSION=1 or link to CMake target "gsl::gsl-lite-v1"
[ERROR] In file included from ./source/main.cpp:10:
./lib/gsl-lite/include/gsl-lite/gsl-lite.hpp:22:3: error: #error Header <gsl-lite/gsl-lite.hpp> requires version 1 defaults; set gsl_CONFIG_DEFAULTS_VERSION=1 or link to CMake target "gsl::gsl-lite-v1"
   22 | # error Header <gsl-lite/gsl-lite.hpp> requires version 1 defaults; set gsl_CONFIG_DEFAULTS_VERSION=1 or link to CMake target "gsl::gsl-lite-v1"
      |   ^~~~~
```
- I do _not_ use `narrow<>()`
    - Nor do I use anything that relies on/uses iostreams (mostly due to the increase in code size, which is prohibitively large on my embedded device)
- I _do_ still want to use other parts of gsl-lite

The compilation errors I have are _without_ using anything from gsl or gsl-lite, merely #including the gsl-lite header. Hopefully this helps clarify!

**Comment by petamas** [comment]
OK, now I do not understand how it compiled on my end. I'll look into it.

**Comment by mbeutel** [comment]
Indeed, I overlooked the fact that the error occurs in the header itself.

I'm uncertain what to do with the `narrow<>()` call in `write_to_stream()`. One could argue that, being in a stream operator, it should stick to the stream error handling semantics, which means setting the fail bit if something goes wrong (which *can* cause an exception to be thrown if the stream is configured accordingly). Also, one might say that the check is guarding against something that *should* never happen because `std::streamsize` is unlikely to ever be smaller than `std::ptrdiff_t` and `spn.length()` must fit in `std::ptrdiff_t`, and hence the most appropriate check would be an `assert()` or `narrow_failfast<>()`.

Opinions?

Either way, this again reinforces the need to have continuous testing also with exceptions disabled (cf. #264).

**Comment by petamas** [comment]
I like the idea of setting the fail bit, because it matches the ideas of the streams library. However, using narrow_failfast() would definitely be easier, since we wouldn't have to reimplement the "is this narrowing?" logic (which is already implemented twice, once in narrow, and once in narrow_failfast). Also, I agree it's highly unlikely that `spn.length()` does not fit into an `std::streamsize`.

So the real question is: do we want to spend more time implementing the more robust, conceptionally sound solution (failbit), or do we want to do the quicker solution, which may lead to problems in some highly unlikely scenarios?

**Comment by mbeutel** [comment]
> since we wouldn't have to reimplement the "is this narrowing?" logic (which is already implemented twice, once in `narrow`, and once in `narrow_failfast`).

(I think this is tolerable as long as it's just one function, but I'm certainly not happy about it. And it would get worse if we ever decided to add a third variant `try_narrow<>()` which would return an error code. I've taken that route in [slowmath](https://github.com/mbeutel/slowmath#why-slowmath), where I avoid implementing every function multiple times, but I'd rather not introduce the required error handling machinery here.)


> So the real question is: do we want to spend more time implementing the more robust, conceptionally sound solution (failbit)

I'm not entirely convinced the failbit approach is "conceptually sound"; but admittedly I fail to come up with a scenario where this problem can occur, so yes, let's just do the simplest thing.
