### ISSUE TITLE
Questions about the conditions for the conversion operators

### ISSUE THREAD

**Issue by petamas** [gsl-lite/gsl-lite#260]
The different conversion operators have different conditions in their `enable_if`:

- explicit lvalue: `std::is_constructible<U, T const &>::value && !std::is_convertible<T, U>::value`
- explicit rvalue: `std::is_constructible<U, T>::value && !std::is_convertible<T, U>::value`
- implicit lvalue: `std::is_constructible<U, T const &>::value && std::is_convertible<T, U>::value`
- implicit rvalue: `std::is_convertible<T, U>::value`

These seem inconsistent, or at least not trivial for me. My questions:
- why is `T const &` being used for lvalue constructibility test?
- why is `is_constructible` tested for one of the implicit operators, but not the other?

**Comment by mbeutel** [comment]
- why `T const &`: `std::is_constructible<std::unique_ptr<Base>, std::unique_ptr<Derived>>::value`; is `true`, but `std::is_constructible<std::unique_ptr<Base>, std::unique_ptr<Derived> const &>::value` is `false` because `std::unique_ptr<>` is not copyable, hence no lvalue conversion can be provided.
- `is_constructible`: I think for implicit lvalue we could equivalently test `std::is_convertible<T const &, U>::value`. (For consistency we should then also express the explicit lvalue test as `std::is_constructible<U, T const &>::value && !std::is_convertible<T const &, U>::value`.)

**Comment by petamas** [comment]
`T const&`: ok, I understand

So, if we modified for consistency, we could use these conditions?
- explicit lvalue: `std::is_constructible<U, T const &>::value && !std::is_convertible<T const &, U>::value`
- explicit rvalue: `std::is_constructible<U, T>::value && !std::is_convertible<T, U>::value`
- implicit lvalue: `std::is_convertible<T const &, U>::value`
- implicit rvalue: `std::is_convertible<T, U>::value`

**Comment by mbeutel** [comment]
Exactly.

**Comment by petamas** [comment]
Thanks! Last question: why `is_convertible<T, U>` instead of `is_convertible<T &&, U>`?

**Comment by mbeutel** [comment]
[https://en.cppreference.com/w/cpp/types/is_convertible](https://en.cppreference.com/w/cpp/types/is_convertible) defines `is_convertible<From, To>` in terms of [`std::declval<>()`](https://en.cppreference.com/w/cpp/utility/declval), which returns [`std::add_rvalue_reference_t<T>`](https://en.cppreference.com/w/cpp/types/add_reference). Hence there should be no discernible difference between `is_convertible<From, To>` and `is_convertible<From&&, To>`.

**Comment by petamas** [comment]
I see - I read both pages yesterday, but did not realize it. Thanks!
