### ISSUE TITLE
What is the purpose of not_null_data?

### ISSUE THREAD

**Issue by petamas** [gsl-lite/gsl-lite#261]
It seems to me that having `not_null_data` would make `not_null`s constructors/assignment operators from `not_null<T>` and `not_null<U>` easier to implement, but:
- it's inconsistent whether the `not_null_data` constructors/operators do a null-check
- `not_null`'s constructors/operators read/write `data.ptr_` directly, not calling `not_null_data`'s already implemented operations

So, what was the purpose of the class? Should we simplify the constructors/assignment operators of `not_null` by moving all the checks to `not_null_data` and implementing `not_null`'s operations based on `not_null_data`'s, `=default`ing when we can?

**Comment by mbeutel** [comment]
Yeah, I should have left a few comments when I came up with this. I cannot remember exactly. But I guarantee loads of fun with VC2010/2012/2013 when dabbling with `not_null_data<>`.

I think `not_null_data<>` emerged to satisfy the following "impossible" set of requirements:

(1) `not_null<T>` should be copyable if and only if `T` is copyable
(2) the copy constructor needs to check the preconditions
(3) the type traits should correctly diagnose whether `not_null<T>` is copy-constructible without triggering a hard failure if it isn't
(4) we don't want to specialize the full type for copyable and non-copyable types

With `not_null_data<>` we get all these by just writing
```c++
#if gsl_HAVE( IS_DEFAULT )
    gsl_constexpr14 not_null( not_null const & other ) = default;
    gsl_constexpr14 not_null & operator=( not_null const & other ) = default;
#endif
```

**Comment by petamas** [comment]
OK, I think I understand the original motivation. But if we have `not_null_data`, why do we provide copy/move operations to `not_null`, why don't we simply "rule of zero" it? `not_null_data` would take care of everything, and we would only need to work on the converting constructors. (AFAIK template `not_null<U>` constructors do not disable auto-generated copy/move/etc.)

**Comment by petamas** [comment]
Also, you haven't explained the inconsistency of contract checks in `not_null_data`: the copy operations do a null-check, while the move operations do not. (Instead, the hand-rolled `not_null` move operations do the check; also, the copy or copy-like converting constructors also do the null-check, and bypass `not_null_data`'s constructors.

**Comment by mbeutel** [comment]
> Or is some weird VS bug the reason?

Several of the peculiarities of `not_null_data<>` boil down to that, yes. You can watch me bang my head against the AppVeyor output in #208; I fixed the issues only after I set up a VM with VS 2010, 2012, and 2013.

You'd think you could do with "rule of zero", or that some `= default` or `= delete` are unnecessary; but then you try it and find that the type traits report wrong results for some particular VS version. As I said, loads of fun. But of course I don't claim it cannot be improved.

As to why I avoid delegating more precondition/postcondition checks to `not_null_data<>`: I consider precondition/postcondition checks part of the function signature, and hence I prefer them to be immediately visible to a reader of the function to emphasize their contract-documenting nature. That is, I prefer the more verbose
```c++
namespace detail {
std::pair<BigInt, BigInt> div(BigInt n, BigInt d)
{
    // ...
}
} // namespace detail
BigInt operator /(BigInt n, BigInt d)
{
    gsl_Expects(d != 0);
    auto [q, _] = detail::div(n, d);
    return q;
}
BigInt operator %(BigInt n, BigInt d)
{
    gsl_Expects(d != 0);
    auto [_, r] = detail::div(n, d);
    return r;
}
```
over the terser
```c++
namespace detail {
std::pair<BigInt, BigInt> div(BigInt n, BigInt d)
{
    gsl_Expects(d != 0);
    // ...
}
} // namespace detail
BigInt operator /(BigInt n, BigInt d)
{
    auto [q, _] = detail::div(n, d);
    return q;
}
BigInt operator %(BigInt n, BigInt d)
{
    auto [_, r] = detail::div(n, d);
    return r;
}
```

I'm not sure about the status of the Contracts proposal, but I think contracts weren't composable, i.e. one had to be verbose and write
```c++
BigInt operator /(BigInt n, BigInt d)
[[ expects: d != 0 ]]
{
    auto [q, _] = detail::div(n, d);
    return q;
}
BigInt operator %(BigInt n, BigInt d)
[[ expects: d != 0 ]]
{
    auto [_, r] = detail::div(n, d);
    return r;
}
```

There are checks in `not_null_data<>` copy constructors and copy assignment operators *only* because `not_null<>` copy constructors *had* to be auto-generated for the reasons explained above.

**Comment by petamas** [comment]
Thanks for the explanation, I think I understand the reasons. I can't promise I won't waste some time trying to simplify it, but at least I'll be prepared now.

Regarding the expectations: I understand, and will adhere to this in my potential modifications.
