### ISSUE TITLE
Add -fno-exceptions builds to CI

### ISSUE THREAD

**Issue by petamas** [gsl-lite/gsl-lite#264]
There were multiple issues where GSL-Lite did not compile if exception support was turned off: #216, #252, #254 .

To prevent these kinds of issues, a new mode (apart from v0/v1) should be introduced to our CI pipeline.

See my proposal [here](https://github.com/gsl-lite/gsl-lite/issues/252#issuecomment-664428856):

> I think instead of having a separate test suite, we should adapt our already existing test suite to be able to be tested with or without exceptions:
> 
> * introduce a new macro called `EXPECT_FAIL` in `gsl_lite.t.hpp`
> * if exceptions are enabled, `EXPECT_FAIL` should be defined using `EXPECT_THROW`
> * if exceptions are disabled, `EXPECT_FAIL` should be defined using an implementation of `fail_fast_assert_handler ` (eg. `fail_fast_assert_handler` sets a global error flag, and `EXPECT_FAIL` contains an `EXPECT` on that)
> * replace `EXPECT_THROW` with `EXPECT_FAIL` in gsl_lite.t.hpp (where applicable, i.e. everywhere except test for `narrow`
> * modify the cmake files to build&run all tests both with and without exceptions, defining the corresponding `gsl_CONFIG_CONTRACT_VIOLATION_XXX` macro

**Comment by mbeutel** [comment]
Of course I'm all for having CI coverage of the no-exception mode. However, a question:

What benefit would we get from modifying the test suite to run with exceptions disabled? The semantic behavior of *gsl-lite* doesn't depend on the contract violation handling mode, so given that we have working tests in throw-on-contract-violation mode, wouldn't it be enough if the tests *compiled* in (exception-less) fail-fast mode?

**Comment by petamas** [comment]
I haven't checked, but I'm almost sure that building the tests is slower than running them, so in my opinion the real question is: why NOT run the tests in exceptionless mode?
Naturally, for my purposes, it's enough to build the tests, but I see no reason not to run them.

**Comment by mbeutel** [comment]
> I haven't checked, but I'm almost sure that building the tests is slower than running them, so in my opinion the real question is: why NOT run the tests in exceptionless mode?

Because then we don't need to adapt the test suite to exception-less execution. No need for `EXPECT_FAIL()`, no need to work around tests that run into UB if precondition assertions don't abort on violation.

**Comment by mbeutel** [comment]
Commits https://github.com/gsl-lite/gsl-lite/commit/d3c06ae93fef8f05c2f3a37c79356d9a77e825a9, https://github.com/gsl-lite/gsl-lite/commit/501aefdf2c0712866fadb0dfe80785344e778441, https://github.com/gsl-lite/gsl-lite/commit/39ce5470a73f99e8174b563244a846270bd9382b, https://github.com/gsl-lite/gsl-lite/commit/1e177efd988c30779bbb38dcc66b25efced32e1f (with some subsequent fixes) have now added targets that are compiled in no-exception mode.

As explained in the source code, we only run tests for targets with exceptions enabled. Our local copy of [*lest*](https://github.com/martinmoene/lest) has been modified to permit *compilation* without exceptions (so we can test compiling gsl-lite without exceptions available), but the no-exception tests will not run correctly because lest relies on exceptions for running tests and therefore cannot function correctly without.

I consider this sufficient for our purposes. If we wanted to have workable runtime tests for no-exception mode, we'd need to transition to a testing framework which supports death tests. (A stop-gap modification of *lest*, as suggested by @petamas, might be possible, but not a clean solution in my view.
